### ISSUE TITLE
Definir modelo para publicação de HIGHLIGHTS 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/PC-Programs#3159]
SPS
- [x] Documentar no SPS https://github.com/scieloorg/scielo_publishing_schema/issues/864

PC Programs
- [x] Configurar os elementos e atributos no Markup 

Packtools
- [ ] Apresentar os dados no texto completo. https://github.com/scieloorg/packtools/issues/217

Web
- [ ] Apresentar os dados no texto completo. https://github.com/scieloorg/Web/issues/705

Não aplicáveis
- Validar os dados no XPM 
- Armazenar os dados na base de dados

**Comment by robertatakenaka** [comment]
No markup, no formulário para preencher os atributos de `xmlabstr` foi adicionado o atributo `absttype` com valores: `summary` (para o resumo padrão), `key-points` (para destaques/highlights) e `graphic abstract` (para resumos visuais)

![Captura de Tela 2020-02-03 às 14 26 32](https://user-images.githubusercontent.com/505143/73675817-e8e8e200-4691-11ea-9950-e5d9905c1c45.png)
![Captura de Tela 2020-02-03 às 14 25 47](https://user-images.githubusercontent.com/505143/73675822-eab2a580-4691-11ea-844f-6766348dfdcf.png)
![Captura de Tela 2020-02-03 às 14 25 01](https://user-images.githubusercontent.com/505143/73675832-ed14ff80-4691-11ea-88ef-da810183aaf0.png)

**Comment by robertatakenaka** [comment]
Fechando, as pendências relacionadas com highlights estão em outros repositórios.
